# Generated by Django 4.0 on 2024-06-20 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 17, 27, 51, 991503)),
        ),
    ]
